
package view;

import Controller.SQLConnect;
import Controller.SQLregistro;
import Model.Registro;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class Panelrecetas extends javax.swing.JFrame {

    /**
     * Creates new form Panelrecetas
     */
    public Panelrecetas() {
    initComponents();
       tablarecetas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
       
    }      
    
    private void CleanTableRecipes() {
         DefaultTableModel model = (DefaultTableModel) tablarecetas.getModel();    
        while (tablarecetas.getRowCount() >0){
            model.removeRow(0);
        }
    }    
    private boolean ExisteReceta (){
     
            return false;
     
            }    
  
      
    private void FillTablerooms() {
        try {
            SQLConnect objConnect = new SQLConnect();
            SQLregistro objregistro = new SQLregistro(objConnect);

            List<Registro> registros = objregistro.ConsultaRecetas();


            CleanTableRecipes();

            for (Registro obj : registros) {

                    var model = (DefaultTableModel) tablarecetas.getModel();
                    model.addRow(new Object[]{
                         obj.getNombre(),obj.getTiporeceta(), obj.getSabor(),
                        obj.getPrecio(), obj.getRecetapap()
                    });
                }
            

            if (objConnect != null)
                objConnect.close();

            }catch (SQLException ex) {
            System.out.println("Exception Thrown: " + ex);
            // Logger.getLogger(PanelCheckin.class.getName()).log(Level.SEVERE, null, ex);
        }
}
 private void FillTextArea() {
        try {
            SQLConnect objConnect = new SQLConnect();
            SQLregistro objregistro = new SQLregistro(objConnect);

            List<Registro> registros = objregistro.ConsultaRecetas();


            

            for (Registro obj : registros) {

                    var model = (DefaultTableModel) tablarecetas.getModel();
                    model.addRow(new Object[]{
                         obj.getNombre(),obj.getTiporeceta(), obj.getSabor(),
                        obj.getPrecio()
                    });
                }
            

            if (objConnect != null)
                objConnect.close();

            }catch (SQLException ex) {
            System.out.println("Exception Thrown: " + ex);
            // Logger.getLogger(PanelCheckin.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    private void CleandataAgregar(){
        txtnombre.setText(null);
        txtprecio.setText(null);
        combosabor.setSelectedItem(null);
        combotipo.setSelectedItem(null);
        txtreceta.setText(null);
    }
    private void CleandataPanel(){
        
      
        
        combosabor.setSelectedItem(null);
        combotipo.setSelectedItem(null);
        txtnombre.setText(null);
        txtprecio.setText(null);
        txtreceta.setText(null);
        
        DefaultTableModel dm = (DefaultTableModel)tablarecetas.getModel();
        while(dm.getRowCount() > 0)
        {
        dm.removeRow(0);
        }
        DefaultTableModel md = (DefaultTableModel)tablarecetas.getModel();
        while(md.getRowCount() > 0)
        {
        md.removeRow(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtprecio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        combosabor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        combotipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtreceta = new javax.swing.JTextArea();
        botonlimpiar = new javax.swing.JButton();
        botonagregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablarecetas = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        botongeslimpiar = new javax.swing.JButton();
        botongesborrar = new javax.swing.JButton();
        consultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 102, 255));
        titulo.setText("Añadir Recetas");

        titulo1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(0, 102, 255));
        titulo1.setText("Gestionar Recetas");

        jLabel1.setText("Nombre:");

        jLabel4.setText("Precio:");

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });

        jLabel2.setText("Sabor:");

        combosabor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dulce", "Salado" }));

        jLabel3.setText("Tipo:");

        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vegetariana", "Vegana", "Carnivora" }));

        jLabel5.setText("Receta");

        txtreceta.setColumns(20);
        txtreceta.setRows(5);
        jScrollPane2.setViewportView(txtreceta);

        botonlimpiar.setText("Limpiar");
        botonlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonlimpiarActionPerformed(evt);
            }
        });

        botonagregar.setText("Agregar");
        botonagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonagregarActionPerformed(evt);
            }
        });

        tablarecetas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "nombre", "tipo", "sabor", "precio", "receta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablarecetas.getTableHeader().setReorderingAllowed(false);
        tablarecetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablarecetasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablarecetas);

        jLabel6.setText("Receta:");

        botongeslimpiar.setText("Limpiar");
        botongeslimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botongeslimpiarActionPerformed(evt);
            }
        });

        botongesborrar.setText("Borrar");
        botongesborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botongesborrarActionPerformed(evt);
            }
        });

        consultar.setText("consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo1)
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(botonlimpiar)
                                .addGap(93, 93, 93)
                                .addComponent(botonagregar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combosabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(botongeslimpiar)
                                .addGap(31, 31, 31)
                                .addComponent(botongesborrar)
                                .addGap(18, 18, 18)
                                .addComponent(consultar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6)))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonlimpiar)
                            .addComponent(botonagregar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titulo1)
                            .addComponent(titulo))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(combosabor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botongeslimpiar)
                    .addComponent(botongesborrar)
                    .addComponent(consultar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void botonlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonlimpiarActionPerformed
        // TODO add your handling code here:
        CleandataAgregar();

    }//GEN-LAST:event_botonlimpiarActionPerformed

    private void botonagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonagregarActionPerformed
        // TODO add your handling code here:
        if (txtnombre.getText().isEmpty() || txtprecio.getText().isEmpty() || txtreceta.getText().isEmpty() || combotipo.getSelectedItem() == null || combosabor.getSelectedItem() == null){
            JOptionPane.showMessageDialog(null, "Ingrese todos los campos. Intente de nuevo","Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            if (!ExisteReceta()){
                String nombre = txtnombre.getText();
                String receta = txtreceta.getText();
                Float precio = Float.valueOf(txtprecio.getText());
                String sabor = combosabor.getSelectedItem().toString();
                String tipo = combotipo.getSelectedItem().toString();
                Registro p5 = new Registro (nombre, tipo, sabor, receta, precio);
                try {
                    SQLConnect objConnect = new SQLConnect();
                    SQLregistro objusuario = new SQLregistro(objConnect);
                    objusuario.InsertaRegistro(p5);

                    if (objConnect != null)
                    objConnect.close();
                    objConnect = null;
                    objusuario = null;
                } catch (SQLException ex) {
                 Logger.getLogger(Panelrecetas.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_botonagregarActionPerformed

    private void botongeslimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botongeslimpiarActionPerformed
        CleandataPanel();

    }//GEN-LAST:event_botongeslimpiarActionPerformed

    private void botongesborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botongesborrarActionPerformed
        // TODO add your handling code here:
        int row = tablarecetas.getSelectedRow();
        if (row <0){
            JOptionPane.showMessageDialog(new JFrame(), "Por favor seleccione una Fila","Informacion", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            DefaultTableModel model = (DefaultTableModel) tablarecetas.getModel();
            model.removeRow(row);
        }
    }//GEN-LAST:event_botongesborrarActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        FillTablerooms();
    }//GEN-LAST:event_consultarActionPerformed

    private void tablarecetasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablarecetasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablarecetasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panelrecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panelrecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panelrecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panelrecetas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panelrecetas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonagregar;
    private javax.swing.JButton botongesborrar;
    private javax.swing.JButton botongeslimpiar;
    private javax.swing.JButton botonlimpiar;
    private javax.swing.JComboBox<String> combosabor;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JButton consultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablarecetas;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextArea txtreceta;
    // End of variables declaration//GEN-END:variables
}
